
import React from 'react';

const Analytics: React.FC = () => {
  return (
    <div className="p-8 text-white">
      <h1 className="text-4xl font-bold mb-4">Analytics & History</h1>
      <p className="text-lg text-brand-gray">
        Review past queries, system performance, and operational insights generated by MAHER AI.
      </p>
      <div className="mt-8 p-12 border-2 border-dashed border-brand-light-blue/30 rounded-lg text-center">
        <h2 className="text-2xl font-semibold text-brand-light-gray">Dashboard Coming Soon</h2>
        <p className="text-brand-gray mt-2">Detailed analytics and conversation history will be displayed here.</p>
      </div>
    </div>
  );
};

export default Analytics;
